name: Main

on:
  push:
    branches:
      - "*"
  delete:
    branches:
      - "*"

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: nelonoel/branch-name@v1
      - uses: actions/checkout@v2
      - name: CI/CD
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_WEBSITE_USERNAME: ${{ secrets.GITHUB_WEBSITE_USERNAME }}
          GITHUB_WEBSITE_TOKEN: ${{ secrets.GITHUB_WEBSITE_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          TINIFY_KEY: ${{ secrets.TINIFY_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GOOGLE_PAGESPEED_KEY: ${{ secrets.GOOGLE_PAGESPEED_KEY }}
          YANDEX_BOT_EMAIL: ${{ secrets.YANDEX_BOT_EMAIL }}
          YANDEX_BOT_TOKEN: ${{ secrets.YANDEX_BOT_TOKEN }}
          GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          ./cicd \
            ${{ github.workflow }} \
            ${{ github.event_name }} \
            ${{ github.event.ref }}
